### ISSUE TITLE
Show Conversion Ratio On Mint

### ISSUE THREAD

**Issue by junkim012** [Ion-Protocol/nucleus-app#74]
## Problem
- Currently, when people deposit a token, the conversion ratio from the deposit token to the mint token is unclear.
- Ex)
    - Assume 1 ssETH = 1.1 WETH
    - When I deposit 1 WETH, I get 0.91 ssETH.
    - If the user doesn’t see the 1 ssETH = 1.1WETH conversion, the user will be confused as to why they received 0.91 ssETH.

## Solution
- Show the value of the mint asset in terms of the deposit asset in the UI.
    - If WETH is selected as the deposit asset,
        - 1.1 WETH/ssETH
    - IF wstETH is selected as the deposit asset,
        - 0.9 WETH/ssETH
    - This conversion rate is the `rateInQuote` value. 
 
- Instead of ‘Price’, put ‘Exchange Rate’.
- Remove the drop down to the right.
- The denomination of the price should change depending on which deposit asset is chosen.
## References
<img width="608" alt="Screenshot 2024-09-24 at 3 28 31 PM" src="https://github.com/user-attachments/assets/17d7b3fd-2b43-492a-b694-ed1f9cfde3e7">

**Comment by 0xRowdy** [comment]
@junkim012 Based on my review of the current UI and design, I believe a few things are missing.

Currently, the UI only displays the fee.
![Screenshot 2024-10-23 at 8 33 36 AM](https://github.com/user-attachments/assets/088c64c8-a77d-44ef-8318-5f5694299970)

Compared to designs in [Figma](https://www.figma.com/design/9o1l6YKZ5yKtCgGeI8rYkp/Nucleus?node-id=10208-120628&node-type=canvas&t=tEh9oQEGQ46JGpar-0).
- Price has been updated to Exchange Rate with tooltip
- Dropdown is removed
- Total displayed in USD

![Screenshot 2024-10-23 at 8 31 21 AM](https://github.com/user-attachments/assets/2b0d2bcd-df6e-43fd-87df-d60f777870d3)

Goals of this ticket
- [ ] Include Exchange Rate with tooltip

Outstanding difs between Design
- [ ] Total in USD

**Comment by 0xRowdy** [comment]
PR is up for this, but WETH is hardcoded because we are currently missing the vault base asset in the store.
Vault base asset should be used for the Exchange Rate.

> all ETH vaults like ssETH, earnETH, seiyanETH, FETH, etc. have the Accountant.base() return WETH

We can push this up and create another ticket for a fast follow-up to fetch that data or delay merging this. Hardcoded base asset of WETH shouldn't impact any of the currently deployed vaults live in the UI.
