### ISSUE TITLE
Redemptions Tab

### ISSUE THREAD

**Issue by junkim012** [Ion-Protocol/nucleus-app#88]
## Description
https://www.notion.so/molecularlabs/Nucleus-Frontend-Integration-Docs-7c1c9ccbf2a24398855547d20d8e8830?pvs=4#4600b9510739435b86bf0ab91ded60ee
## Requirements
 ![Image](https://github.com/user-attachments/assets/c49b78f8-6dba-4ec2-9b4e-080c3bdf7a6b)
- The `Price` is the `rateInQuote` WITH the 0.5% fee. 
- The `Recieve` amount shown to the user should be the receive amount of `want` asset calculated with the `Price` (which is inclusive of the ~slippage~  `Withdraw Fee`). 
  - This basically means that the user will receive the exact amount that they see on the UI. 
- This means we don't need a `receive at least` field because `Receive` is the exact amount that the users will get. 
- Instead of `Slippage`, it should be `Withdraw Fee` fixed at 0.5%. 
  - Tooltip: "Withdraw fees applied in order to incentivize solvers to process withdraw orders into arbitrary requested assets."
- `Bridge Fee` is just the fee applied for the bridge. 
  - Do not show the bridge fee if we are withdrawing from the same chain.
- Order 
  - Price
  - Bridge Fee (if crosschain bridging is involved)
  - Withdrawal Fee
  - Deadline
- Path
  - Redeem from Sei receive on Ethereum 
  - Redeem from Sei receive on Sei <- Need Confirmation
- What happens if either of the two transactions (bridge + updateAtomicRequest) fails? 
    - First, call `updateAtomicRequest`, then call bridge second. 
    - If bridge fails -> the UI starts over and prompts the user to `updateAtomicRequest` again. 
      - At this point, the frontend can query the existing request, and if the `offer` `want` `atomicPrice` and `offerAmount` is identical. If it's identical, then skip the `updateAtomicRequest` and go straight to the `bridge`. 
 - What happens when the user already has assets that they want to redeem on destination chain? 
   - This can happen if `bridge` succeeds but `updateAtomicRequest` fails.  
     - Also if `bridge` suceeds but the order has expired which means the asset is still on destination chain. 
     - Also if the user intentionally bridged over assets to mainnet for some reason (through direct smart contract interactions without using the UI). 
   - Solution
     -  Check mainnet balance. If mainnet balance is sufficient for requested withdraw amount, then skip bridge and directly call request. 
     - If mainnet balance is not enough for requested amount, then bridge the diff and directly call request. 
     - If we're not bridging, we should let the user know that we are redeeming the assets from the destination chain directly.  
  

## Outstanding Questions
- Does Sei ecosystem want users to be able to withdraw from Sei into Sei, and not just Sei into Ethereum?

**Comment by 0xRowdy** [comment]
> The want asset must be one of the assets that have been whitelisted as a depositable asset to the BoringVault
I did not see a function in the ABI that appeared to return a whilelist of assets. Is this a value that should be queried from the BoringVault? 

Or is this the same as the defaultEthVaultAssets specified in the Frontend config/networks.ts file?
